# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('street_address', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('recorded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('submitted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('total_raised', models.IntegerField(default=0)),
                ('goal', models.IntegerField(default=1500)),
                ('cash_raised', models.IntegerField(default=0)),
                ('checks_raised', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='revenueTracker.Payment')),
            ],
            bases=('revenueTracker.payment',),
        ),
        migrations.CreateModel(
            name='CheckPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='revenueTracker.Payment')),
                ('check_number', models.CharField(blank=True, max_length=20, null=True)),
                ('routing_number', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
            ],
            bases=('revenueTracker.payment',),
        ),
        migrations.AddField(
            model_name='report',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenueTracker.Student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenueTracker.Report'),
        ),
    ]
