# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenueTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpayment',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='checkpayment',
            name='routing_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='salutation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
